version: "3"

services:
  agamotto-py:
    build:
      dockerfile: agamotto-py.Dockerfile
    restart: always

  agamotto-js:
    build:
      context: ../jigg
      dockerfile: agamotto-js.Dockerfile
    restart: always

  nginx:
    image: nginx
    restart: always
    volumes:
      - ./conf.d/:/etc/nginx/conf.d/
      - ./server.crt:/certs/fullchain.pem
      - ./server.key:/certs/privkey.pem
  
  router:
    build:
      dockerfile: nginx.Dockerfile
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./router.conf.d/:/etc/nginx/conf.d/
      - ./server.crt:/certs/fullchain.pem
      - ./server.key:/certs/privkey.pem
