# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: seal.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nseal.proto\x12\x07tenseal\"4\n\x0e\x42\x46VVectorProto\x12\r\n\x05sizes\x18\x01 \x03(\r\x12\x13\n\x0b\x63iphertexts\x18\x02 \x03(\x0c\"H\n\x0e\x42\x46VTensorProto\x12\r\n\x05shape\x18\x01 \x03(\r\x12\x13\n\x0b\x63iphertexts\x18\x02 \x03(\x0c\x12\x12\n\nbatch_size\x18\x03 \x01(\r\"D\n\x0f\x43KKSVectorProto\x12\r\n\x05sizes\x18\x01 \x03(\r\x12\x13\n\x0b\x63iphertexts\x18\x02 \x03(\x0c\x12\r\n\x05scale\x18\x03 \x01(\x01\"X\n\x0f\x43KKSTensorProto\x12\r\n\x05shape\x18\x01 \x03(\r\x12\x13\n\x0b\x63iphertexts\x18\x02 \x03(\x0c\x12\r\n\x05scale\x18\x03 \x01(\x01\x12\x12\n\nbatch_size\x18\x04 \x01(\r\"f\n\x13TenSEALPrivateProto\x12\x12\n\nsecret_key\x18\x01 \x01(\x0c\x12\x1c\n\x14relin_keys_generated\x18\x02 \x01(\x08\x12\x1d\n\x15galois_keys_generated\x18\x03 \x01(\x08\"t\n\x12TenSEALPublicProto\x12\x12\n\npublic_key\x18\x01 \x01(\x0c\x12\x12\n\nauto_flags\x18\x02 \x01(\r\x12\r\n\x05scale\x18\x03 \x01(\x01\x12\x12\n\nrelin_keys\x18\x04 \x01(\x0c\x12\x13\n\x0bgalois_keys\x18\x05 \x01(\x0c\"\xb9\x01\n\x13TenSEALContextProto\x12\x1d\n\x15\x65ncryption_parameters\x18\x01 \x01(\x0c\x12\x33\n\x0epublic_context\x18\x02 \x01(\x0b\x32\x1b.tenseal.TenSEALPublicProto\x12\x35\n\x0fprivate_context\x18\x03 \x01(\x0b\x32\x1c.tenseal.TenSEALPrivateProto\x12\x17\n\x0f\x65ncryption_type\x18\x04 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'seal_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BFVVECTORPROTO._serialized_start=23
  _BFVVECTORPROTO._serialized_end=75
  _BFVTENSORPROTO._serialized_start=77
  _BFVTENSORPROTO._serialized_end=149
  _CKKSVECTORPROTO._serialized_start=151
  _CKKSVECTORPROTO._serialized_end=219
  _CKKSTENSORPROTO._serialized_start=221
  _CKKSTENSORPROTO._serialized_end=309
  _TENSEALPRIVATEPROTO._serialized_start=311
  _TENSEALPRIVATEPROTO._serialized_end=413
  _TENSEALPUBLICPROTO._serialized_start=415
  _TENSEALPUBLICPROTO._serialized_end=531
  _TENSEALCONTEXTPROTO._serialized_start=534
  _TENSEALCONTEXTPROTO._serialized_end=719
# @@protoc_insertion_point(module_scope)
